name: Build ffmpeg
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: ffmpeg
        run: |
          cd C:\vcpkg
          vcpkg update
          git pull
          vcpkg update
          vcpkg install ffmpeg
